import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import Switch from "@mui/material/Switch";

const label = {inputProps: {"aria-label": "Switch demo"}};
export default function Home() {
    return (
        <>
            <Head>
                <title>Xoje Developer</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.container}>
                    <div>
                        <span>With default Theme:</span>
                    </div>
                    <Switch {...label} defaultChecked/>
                    <Switch {...label} />
                    <Switch {...label} disabled defaultChecked/>
                </div>
            </main>
        </>
    )
}
